config/routes.rb
Rails.application.routes.draw do
root to: 'breweries#index'
  resources :beers # NHO: one idea is to have only /beers route to the beers index
  resources :breweries do
    resources :beers, only: [:index, :show, :new, :create]
  end
  resources :restaurants do
    resources :beers, only: [:index, :show, :new, :create]
  end
end

app/models/beer.rb
class Beer < ActiveRecord::Base
  # NHO: one thing to consider in the future is the design choice about this relationship
  # As you currently have it, a beer that belongs to a brewery, has in essence no knowledge of any beer associated to a restuarant
  # This is totally and completely acceptable, it just means you might end up with duplicates...

  # One way you could avoid duplication is by setting up polymorphic relationships between Beer, Restaurant, and Brewery
  # though that would require a big application rearchitecture
  belongs_to :brewery
  belongs_to :restaurant
  validates :brewery, presence: true # NHO: this might be hard to validate if a beer is also associated to a Restaurant
  validates :name, presence: true
end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  # NHO: might consider adding a `dependent: :destroy` option on this relationship to prevent orphaned beers
  has_many :beers
  validates :name, presence: true # NHO: validations, nice!
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  # NHO: might consider adding a `dependent: :destroy` option on this relationship to prevent orphaned beers
  has_many :beers
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController

  def index
    @beers = Beer.all
  end

  def new
    @beer = Beer.new
  end

  def create
    # NHO: could be a great place for a code comment
    @brewery = Brewery.find_or_initialize_by(name:params[:beer][:brewery])
    @brewery.save # NHO: opportunity to check if this @brewery saved sucessfully
    @beer = @brewery.beers.create!(beer_params)
    redirect_to @beer
  end

  def show
    @beer = Beer.find(params[:id])
  end

  def edit
    @beer = Beer.find(params[:id])
  end

  def update
    @beer = Beer.find(params[:id])
    @beer.update(beer_params)

    redirect_to @beer
  end

  def destroy
    @beer = Beer.find(params[:id])
    @beer.destroy

    redirect_to beers_path
  end

  def beer_params
    params.require(:beer).permit(:name, :style, :booze_id, :booze_type)
  end

end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController

  def index
    @breweries = Brewery.all
  end

  def new
    @brewery = Brewery.new
  end

  def create
    @brewery = Brewery.create!(brewery_params)

    redirect_to @brewery
  end

  def show
    @brewery = Brewery.find(params[:id])
  end

  def edit
    @brewery = Brewery.find(params[:id])
  end

  def update
    @brewery = Brewery.find(params[:id])
    @brewery.update(brewery_params)

    redirect_to @brewery
  end

  def destroy
    @brewery = Brewery.find(params[:id])
    @brewery.destroy

    redirect_to breweries_path
  end

  def brewery_params
    params.require(:brewery).permit(:name, :neighborhood, :beers, :photo_url)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create!(restaurant_params)

    redirect_to @restaurant
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)

    redirect_to @restaurant
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    redirect_to restaurants_path
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :neighborhood, :beers, :photo_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/beers/edit.html.erb
<h2>Edit Beer <%= link_to "(+)", new_beer_path %></h2>

<%= form_for @beer do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :brewery %>
<%= f.text_field :brewery %>

<%= f.label :style %>
<%= f.text_field :style %>

<%= f.submit %>
<% end %>

<%= link_to "Delete!", @beer, method: :delete, class: "delete" %>

app/views/beers/index.html.erb
<h2>Beers <%= link_to "(+)", new_beer_path %></h2>

<ul>
  <% @beers.each do |beer| %>
  <li><%= link_to "#{beer.name} - #{beer.brewery.name}", beer %></li>
  <% end %>
</ul>

app/views/beers/new.html.erb
<!-- NHO: think we can display the beer or restaurant name we are trying to associated this beer to -->
<h2>New Beer for</h2>

<%= form_for @beer do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<!-- NHO: if you want to associate the beer to a brewery,
you need to do the association in the controller instead of a collecting a string
or you could make this a multiple select field, populated with all Breweries -->
<%= f.label :brewery %>
<%= f.text_field :brewery %>

<%= f.label :style %>
<%= f.text_field :style %>

<%= f.submit %>
<% end %>

app/views/beers/show.html.erb
<h2><%= @beer.name %> <%= link_to "(edit)", edit_beer_path(@beer) %></h2>
<h4><%= @beer.brewery.name %></h4>
<h4><%= @beer.style %></h4>

<!-- NHO: need to access a propert of the brewery object associated with @beer  -->
Brewery: <%= @beer.brewery.name %></br>

app/views/breweries/edit.html.erb
<h2>Edit Brewery</h2>

<%= form_for @brewery do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :neighborhood %>
<%= f.text_field :neighborhood %>

<!-- NHO: what's the purpose of this beer field? -->
<%= f.label :beer %>
<%= f.text_field :beer %>

<%= f.label :photo_url %>
<%= f.text_field :photo_url %>

<%= f.submit %>
<% end %>

<%= link_to "Delete", @brewery, method: :delete, class: "delete" %>

app/views/breweries/index.html.erb
<h2>Breweries <%= link_to "(+)", new_brewery_path %></h2>

<ul>
<% @breweries.each do |brewery| %>
<li>
  <%= link_to brewery.name, brewery %>
</li>
<% end %>
</ul>

app/views/breweries/new.html.erb
<h2>New Brewery</h2>

<%= form_for @brewery do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :neighborhood %>
<%= f.text_field :neighborhood %>

<%= f.label :beer %>
<%= f.text_field :beer %>

<%= f.label :photo_url %>
<%= f.text_field :photo_url %>

<%= f.submit %>
<% end %>

app/views/breweries/show.html.erb
<h2><%= @brewery.name %> <%= link_to "(edit)", edit_brewery_path(@brewery) %></h2>
<h4><%= @brewery.neighborhood %></h4>
<h4><%= @brewery.beer %></h4>


<img class='brewery-photo' src="<%= @brewery.photo_url %>">

<h3>Beers <%= link_to "(+)", new_brewery_beer_path(@brewery) %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Booze Rails</title>
  <link href='https://fonts.googleapis.com/css?family=Oswald:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1><%= link_to "Booze Rails", root_url %></h1>

  <nav>
    <%= link_to "Beer", beers_path %>
    <%= link_to "Breweries", breweries_path %>
    <%= link_to "Restaurants", restaurants_path %>
  </nav>

  <!-- NHO: reminder of the difference between syntaxes for ERB tags  -->
  <% flash.each do|type, message| %>
    <p class="<%= type %>"><%= message %></p>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/restaurants/edit.html.erb
<h2>Edit Restaurant</h2>

<%= form_for @restaurant do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :neighborhood %>
<%= f.text_field :neighborhood %>

<!-- NHO: what's the purpose of this beer field? -->
<%= f.label :beer %>
<%= f.text_field :beer %>

<%= f.label :photo_url %>
<%= f.text_field :photo_url %>

<%= f.submit %>
<% end %>

<%= link_to "Delete", @restaurant, method: :delete, class: "delete" %>

app/views/restaurants/index.html.erb
<h2>Restaurants <%= link_to "(+)", new_restaurant_path %></h2>

<ul>
<% @restaurants.each do |restaurant| %>
<li>
  <%= link_to restaurant.name, restaurant %>
</li>
<% end %>
</ul>

app/views/restaurants/new.html.erb
<h2>New Restaurant</h2>

<%= form_for @restaurant do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :neighborhood %>
<%= f.text_field :neighborhood %>

<%= f.label :beer %>
<%= f.text_field :beer%>

<%= f.label :photo_url %>
<%= f.text_field :photo_url %>

<%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %> <%= link_to "(edit)", edit_restaurant_path(@restaurant) %></h2>
<h4><%= @restaurant.neighborhood %></h4>
<h4><%= @restaurant.beer %></h4>

<img class='restaurant-photo' src="<%= @restaurant.photo_url %>">

<h3>Beers <%= link_to "(+)", new_restaurant_beer_path(@restaurant) %></h3>